import { Text, Grid, Center} from "@mantine/core";
import { BadgeCard } from "@/src/components/productsComponents/mainProd";
import Head from "next/head";

const Events = ({ productsList }) => {

  const styles= {
    select: {
      backgroundColor: "transparet",
      padding: "10px",
      marginBottom: "10px",
      display: "inline",
      marginLeft: "10px",
      fontWeight: "600",
    },
    option: {
      fontWeight: "600",
    },
    title: {
      display: "inline",
      marginLeft: "30px",
      fontWeight: "bold",
      fontSize: "18px"
    },
    wrapper: {
      margin: "0 15px"
    }
  }

  {/* async function handleChange(e) {
    const category = e.target.value;
    if (category != "Compléments Alimentaires") {
      const data = productsList.filter((product)=>product.category.includes(category) )
      setProducts(data);
    } else {
      setProducts(productsList);
    }
  }
  */}

  return (
    <>
      <Head>
        <title>Produits</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
        <h1 >Collection Vitamine D3</h1>
        <Text>  C’est la forme la plus active de vitamine D. Elle se forme dans la peau lorsque celle-ci est exposée à la lumière directe du soleil. La source alimentaire la plus commune est constituée des aliments enrichis en vitamines, principalement les céréales et les produits laitiers. La vitamine D est aussi présente dans les huiles de foie de poisson, les poissons gras, le jaune d’œuf et le foie.  </Text>

    <Center>
     <Grid style={{padding: "30px" }}>
        {productsList &&
          productsList.map((product) => {
            return (
            <Grid.Col sm={4} md={3} key={product.id}>
              <BadgeCard {...product} />
            </Grid.Col>
            );
          })}
    </Grid>
</Center>
    </div>
    </>
  );
};

export default Events;

export async function getServerSideProps() {
  const { products } = await import("../../../data/products.json");
  return {
    props: {
      productsList: products.filter((product)=> product.title.includes("D3")),
    },
  };
}