import { Text, Grid, Center, Button} from "@mantine/core";
import BaseButton from "@/src/components/baseButton";
import { VenteCard } from "@/src/components/productsComponents/mainProd2";
import Head from "next/head";
import { CardsCarousel } from "@/src/components/carousel";
import Image from "next/image";
import Link from "next/link";

const Events = ({ bestSelling }) => {

  const styles= {
    select: {
      backgroundColor: "transparet",
      padding: "10px",
      marginBottom: "10px",
      display: "inline",
      marginLeft: "10px",
      fontWeight: "600",
    },
    banner: {
        backgroundColor: "#ccc",
        height: "150px",
    },
    bannerContent: {
        width: "700px",
        margin: "20px auto"
    },
    option: {
      fontWeight: "600",
    },
    title: {
      display: "inline",
      marginLeft: "30px",
      fontWeight: "bold",
      fontSize: "18px"
    },
    wrapper: {
      margin: "10px 55px"
    }
  }

  return (
    <>
      <Head>
        <title>Produits</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
        <CardsCarousel />
        <div style={styles.wrapper}>
            <h2 style={{marginTop: "20px", color: "#937b44"}}>NOS MEILLEURS VENTES</h2>
            <Grid style={{padding: "30px" }}>
                {bestSelling &&
                bestSelling.map((product) => {
                    return (
                    <Grid.Col sm={6} md={3} key={product.id}>
                        <VenteCard {...product} />
                    </Grid.Col>
                    );
                })}
            </Grid>
            <Grid>
                    <Grid.Col sm={10} offset={1} md={5}>
                        <Image src={"/VIT_D.jpg"} style={{borderRadius: "32px"}} width={500} height={380} />
                    </Grid.Col>
                    <Grid.Col style={{margin: "50px"}} sm={10} md={5}>
                      <h2>DÉCOUVREZ Les Vitamines D3 a plusieurs dosages  </h2>
                    <p>Dosée à 500,1000,4000,50.000 UI par comprimé, elles est très agréable à utiliser au quotidien. La vitamine D contribue au fonctionnement normal du système immunitaire. Elles contribue également à maintenir une ossature et une fonction musculaire normale.</p>
                    <Link href={"/products/d3"}></Link>
        <BaseButton link={"/products/d3"}  text={"Découvrir le produit"} />
                    </Grid.Col>
            </Grid>

            <Grid style={{marginTop: "20px"}}>
                    <Grid.Col style={{paddingLeft: "50px",display: "flex", justifyContent:"center", flexDirection: "column"}} offset={1} sm={10} md={5}>
                    <h1 style={{textTransform: "uppercase"}}>Apple Cider Complex<br /> Newgate </h1>
                    <p>lorem ipsum </p>
                    <BaseButton link={"/products/1"} text={"Découvrir le produit"} />
                    </Grid.Col>
                    <Grid.Col sm={10}  md={5}>
                        <Image src={"/appl2.jpg"} width={500} height={500} />
                    </Grid.Col>
            </Grid>

            <section styles={styles.banner}>
            LA MAJORITÉ DE NOS PRODUITS SONT
                <Grid style={styles.bannerContent}>
                    <Grid.Col span={2}><Image src={"/icon1.png"} width={180} height={180} /><br />SANS OGM</Grid.Col>
                    <Grid.Col span={2}><Image src={"/icon2.png"} width={180} height={180} /><br />VÉGÉTALIEN</Grid.Col>
                    <Grid.Col span={2}><Image src={"/icon3.png"} width={180} height={180} /><br /> SANS GLUTEN</Grid.Col>
                    <Grid.Col span={2}><Image src={"/icon4.png"} width={180} height={180} /><br />SANS PRODUITS LAITIERS</Grid.Col>
                    <Grid.Col span={2}><Image src={"/icon1.png"} width={180} height={180} /><br />HALAL</Grid.Col>
                </Grid>
            </section>

          <section style={{margin: "40px 0", textTransform: "uppercase"}}>
            <Center> <h2>Découvrez nos offres du moment</h2> </Center>
            <Center> <Text>Profitez de nos promotions pour essayer quelque chose de nouveau!</Text> </Center>
          </section>
            <Grid>
                    <Grid.Col style={{border: "1px solid #ccc", padding: "40px"}} offset={1} sm={10}  md={4}>
                      <Center>
                        <Image src={"/NG.jpg"} width={350} height={350} />
                      </Center>
                      <Center>
                        <h3 style={{textAlign: "center"}}>DISPONNIBLE DANS LES PHARMACIES </h3>
                      </Center>
                    </Grid.Col>
                    <Grid.Col style={{border: "1px solid #ccc", padding: "40px"}} offset={1} sm={10}  md={4}>
                      <Center>
                        <Image src={"/az3.jpg"} width={350} height={350} />
                      </Center>
                      <div style={{textAlign: "Center"}}>
                        <h3 style={{textTransform: "uppercase", marginTop:"10px"}}>nos Meilleurs ventes</h3>
                        <Text>Découvrez vos produits préférés dès maintenant sur notre site</Text>
                        <BaseButton link={"/products/8"} text={"Découvrir"} />
                      </div>
                    </Grid.Col>
            </Grid>
        </div>
    </div>
    </>
  );
};

export default Events;

export async function getServerSideProps() {
  const { products } = await import("../../data/products.json");
  return {
    props: {
      bestSelling: products.filter((product)=> product.best),
    },
  };
}