import { Text, Grid, Center} from "@mantine/core";
import { VenteCard } from "@/src/components/productsComponents/mainProd2";
import Head from "next/head";
import { CardsCarousel } from "@/src/components/carousel";
import Image from "next/image";
import Link from "next/link";

const Events = ({ bestSelling }) => {

  const styles= {
    select: {
      backgroundColor: "transparet",
      padding: "10px",
      marginBottom: "10px",
      display: "inline",
      marginLeft: "10px",
      fontWeight: "600",
    },
    banner: {
        backgroundColor: "#ccc",
        height: "150px",
    },
    bannerContent: {
        width: "700px",
        margin: "20px auto"
    },
    option: {
      fontWeight: "600",
    },
    title: {
      display: "inline",
      marginLeft: "30px",
      fontWeight: "bold",
      fontSize: "18px"
    },
    wrapper: {
      margin: "0 15px"
    }
  }

  return (
    <>
      <Head>
        <title>Produits</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
        <CardsCarousel />
        <div style={styles.wrapper}>
            <h1>Meilleurs Ventes</h1>
            <Grid style={{padding: "30px" }}>
                {bestSelling &&
                bestSelling.map((product) => {
                    return (
                    <Grid.Col sm={6} md={3} key={product.id}>
                        <VenteCard {...product} />
                    </Grid.Col>
                    );
                })}
            </Grid>
            <Grid>
                    <Grid.Col sm={10} offset={1} md={5}>
                        <Image src={""} width={500} height={500} />
                    </Grid.Col>
                    <Grid.Col sm={10} md={5}>
                        Text
                    </Grid.Col>
            </Grid>

            <Grid>
                    <Grid.Col offset={1} sm={10} md={5}>
                        Text
                    </Grid.Col>
                    <Grid.Col sm={10}  md={5}>
                        <Image src={""} width={500} height={500} />
                    </Grid.Col>
            </Grid>

            <section styles={styles.banner}>
                Banner
                <Grid style={styles.bannerContent}>
                    <Grid.Col span={2}>Image<br />text</Grid.Col>
                    <Grid.Col span={2}>Image<br />text</Grid.Col>
                    <Grid.Col span={2}>Image<br />text</Grid.Col>
                    <Grid.Col span={2}>Image<br />text</Grid.Col>
                    <Grid.Col span={2}>Image<br />text</Grid.Col>
                </Grid>
            </section>

            <Center> <h3>Title</h3> </Center>
            <Center> <Text>small content</Text> </Center>

            <Grid>
                    <Grid.Col offset={1} sm={10}  md={5}>
                        <Image src={""} width={500} height={500} />
                        <Text>Text</Text>
                    </Grid.Col>
                    <Grid.Col sm={10}  md={5}>
                        <Image src={""} width={500} height={500} />
                        <Text>asdfasdf</Text>
                        <Text>asdfasdf</Text>
                        <Link href={"/products/1"}>asdf</Link>
                    </Grid.Col>
            </Grid>
        </div>
    </div>
    </>
  );
};

export default Events;

export async function getServerSideProps() {
  const { products } = await import("../../data/products.json");
  return {
    props: {
      bestSelling: products.filter((product)=> product.best),
    },
  };
}