import { Text, Grid, Center, Divider} from "@mantine/core";
import { BadgeCard } from "@/src/components/productsComponents/mainProd";
import Head from "next/head";

const Events = ({ productsList }) => {
  {/* const [products, setProducts] = useState(productsList);*/}

  const styles= {
    select: {
      backgroundColor: "transparet",
      padding: "10px",
      marginBottom: "10px",
      display: "inline",
      marginLeft: "10px",
      fontWeight: "600",
    },
    option: {
      fontWeight: "600",
    },
    title: {
      display: "inline",
      marginLeft: "30px",
      fontWeight: "bold",
      fontSize: "18px"
    },
    wrapper: {
      margin: "0 15px"
    }
  }

  {/* async function handleChange(e) {
    const category = e.target.value;
    if (category != "Compléments Alimentaires") {
      const data = productsList.filter((product)=>product.category.includes(category) )
      setProducts(data);
    } else {
      setProducts(productsList);
    }
  }
  */}

  return (
    <>
      <Head>
        <title>Produits</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div style={{margin:"80px"}}>
      <h2 style={{marginTop: "20px",marginBottom:"10px", color: "#937b44"}}>NOS PRODUITS</h2>

<Divider />
     <Grid style={{padding: "30px" }}>
        {productsList &&
          productsList.map((product) => {
            return (
            <Grid.Col xs={3} sm={4} md={2} key={product.id}>
              <BadgeCard {...product} />
            </Grid.Col>
            );
          })}
    </Grid>
    </div>
    </>
  );
};

export default Events;

export async function getServerSideProps() {
  const { products } = await import("../../data/products.json");
  return {
    props: {
      productsList: products,
    },
  };
}