import { GetInTouchSimple } from "@/src/components/contactCom";
import Map from "@/src/components/map"
import Head from "next/head";


const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ padding: "20px" }}>
        <GetInTouchSimple />
      </div>

      <Map />
    </>
  );
}
export default Contact
