import { GetInTouchSimple } from "@/src/components/contactCom";
import Head from "next/head";


const Contact = () => {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ padding: "20px" }}>
        <GetInTouchSimple />
      </div>


<div style={{margin: "20px"}}>

<iframe
    loading="lazy"
    src="https://maps.google.com/maps?q=amb+international+Misserghin&z=17&t=m&output=embed"
    width="100%"
    height="450"
    allowfullscreen=""
></iframe>

</div>
    </>
  );
}
export default Contact
