import { CardsCarousel } from "@/src/components/carousel";
import {  HeroText } from "@/src/components/indexComponents/indAbout";
import { HeroImageBackground } from "@/src/components/indexComponents/indProd";
import { StatsGridIcons } from "@/src/components/indexComponents/indStats";
import Head from "next/head.js";
import { Button, Group,createStyles } from '@mantine/core';
import Link from "next/link";
import { Demo } from "@/src/components/affix";

export default function Home() {
 const useStyles = createStyles((theme) => ({
  Button: {
    backgroundImage: `linear-gradient(135deg, ${theme.colors.teal[9]} 0%, ${
      theme.colors.teal[4]
    } 100%)`,
  },
}))   

  const { classes } = useStyles();
    return (
        <>
            <Head>
                <title>Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container">
                <CardsCarousel />
                <HeroText />
                <HeroImageBackground />
                <div style={{margin: "25px 0"}}></div>
                <StatsGridIcons data={[{title: "Products sold",value: "77", diff: 6},{title: "Products sold",value: "7", diff: 28},{title: "Products sold",value: "777", diff: 8}]} />
                <div style={{justifyContent: "center"}}>
                        <Link href={"/contact"} style={{textDecoration: "none"}}>
                            <Group position="center" mt="xl">
                                <Button type="submit" size="md" className={classes.Button}>
                                    Contact Us
                                </Button>
                            </Group>
                    </Link>
                </div>
            </main>
        </>
    );
}
